[package]
name = "simple-dns"
version = "0.5.2"
authors = ["Ilson Roberto Balliego Junior <ilson.balliego@gmail.com>"]
edition = "2021"
description = "Rust implementation to parse and write DNS packets"
repository = "https://github.com/balliegojr/simple-dns"
license = "MIT"
keywords = ["dns", "parser"]
categories = ["parser-implementations", "network-programming"]


[dependencies]
bitflags = "1.3"
pest = { version = "2.5.7"}
pest_derive = { version = "2.5.7"}

[dev-dependencies]
criterion = "0.3"

[lib]
bench = false

[[bench]]
name = "packet_bench"
harness = false
