name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-dev:
    name: Test Dev on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose

  test-mdns:
    name: Test no default features on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose --no-default-features

  test-release:
    name: Test Release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose --release
